version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: whatif
    ports:
      - "5432:5432"
  api:
    build: ./apps/api
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "3000:3000"
  web:
    build: ./apps/web
    env_file:
      - .env
    ports:
      - "5173:5173"